version: '3.8'

services:
  genesis:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: "nvidia/cuda:12.0-base-ubuntu20.04"
        PYTHON_VERSION: "3.9"
        CMAKE_VERSION: "3.26.1"
        GCC_VERSION: "11"
        ENABLE_LUISARENDER: "ON"
        ENABLE_MOTION_PLANNING: "ON"
        ENABLE_SURFACE_RECONSTRUCTION: "ON"
    image: genesis:latest
    container_name: genesis_simulator
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
      - PYTHONUNBUFFERED=1
    volumes:
      - ./data:/app/data
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
